### ISSUE TITLE
Feature Request - Establish Code Coverage Meter

### ISSUE THREAD

**Issue by weilbith** [Gymetter/mobile-app#10]
# Description

To validate the quality of the written test, a code coverage service should integrated which automatically indicates the projects status. This should then be used to validate pull requests as well to ask for more test cases if needed to reach a higher coverage.

# Tasks

- [ ] Add code coverage service to project.
- [ ] Configure code coverage measurement.
- [ ] Test automation of the service.

# Related Issues

- #2
- #9
