### ISSUE TITLE
Feature Request - Establish Linting and Formatting

### ISSUE THREAD

**Issue by weilbith** [Gymetter/mobile-app#4]
# Description

The development flow should be supported by the integration of a linting tool. This should check the code by static analysis before functional tests run.
Furthermore a code formatting tool should be added to standardize the codes appereance from the start on. Since linter and formatter are going hand-in-hand this includes to add the formatters plugin to the linter, so they do not collide.
Running the linter and formatter should be automated by each developer into his tool-chain. But it needs to be forced for the project itself by hooks and CI later on.

# Tasks
- [ ] Add linter to project.
- [ ] Add formatter to project.
- [ ] Link formatter to linter.
- [ ] Extend CI configuration to run linter.

# Related Issues
- #1
- #3
- #5
