### ISSUE TITLE
Feature Request - Establish Git Hooks

### ISSUE THREAD

**Issue by weilbith** [Gymetter/mobile-app#5]
# Description

For automation of given tasks like running tests, lint the code or format it, hooks on git events should be established. These should prevent the push of not clean or even buggy code to the origin peer, where the CI service would complain about them. This would result in a messy history by fixing commits after CI fails.

# Tasks
- [ ] Add git hook tool.
- [ ] Add code focus tool for formatting.
- [ ] Add hooks:
  - [ ] Check linter before each commit (prevent commit if fails).
  - [ ] Run focused formatter on after each commit.
  - [ ] Run component and integration tests before push (avoid running CI on buggy code when not even working in specialized environment).

# Related Issues
- #2
- #4
