### ISSUE TITLE
Feature Request - Integrate Style Library

### ISSUE THREAD

**Issue by weilbith** [Gymetter/mobile-app#7]
# Description

For upcoming feature development, the style library (defined by gymetter/project#5) should be already integrated and configured. The first version of the appereance including the color scheme should be configured. Also a provided component should be integrated to make sure the integration was successful.

# Tasks

- [ ] Add style library.
- [ ] Inject custom component into DOM.
- [ ] Configure appereance with color scheme.

# Related Issues

- #1
- gymetter/project#5
