### ISSUE TITLE
Feature Request - Open Source Information

### ISSUE THREAD

**Issue by weilbith** [Gymetter/mobile-app#8]
# Description

As each open source project this should also provide a bunch of standard information files. This includes installation instructions, the contribution guide, license file, issue templates and more.

# Tasks

- [ ] Add `INSTALL.md` file.
- [ ] Add `CONTRIBUTING.md` file.
- [ ] Add `LICENSE` file.
- [ ] Add issue and pull request templates:
  - [ ] Feature Request template
  - [ ] Bug Request template
  - [ ] Pull Request template

# Related Issues

- #1
