### ISSUE TITLE
Feature Request - Establish Shields

### ISSUE THREAD

**Issue by weilbith** [Gymetter/mobile-app#9]
# Description

For a good presence of the project _Shields.io_ should be integrated to show the current status of the project. This includes mainly the CI tests, language versions, issues, code coverage etc.

# Tasks

- [ ] Add shields to README:
   - [ ] Last CI run with test results.
   - [ ] Code coverage status.
   - [ ] Framework versions.
   - [ ] Issue status.

# Related Issues

- #1
- #3
- #10
